### ISSUE TITLE
Web app not loading.

### ISSUE THREAD

**Issue by Asag321** [StepKie/MtgCsvHelper#8]
**Describe the bug**
Web app doesn't load for me anymore. Tried it on Chrome and Edge browsers. I see blank page with "Loading" word in the circle but nothing is happening. 

Not sure if its something wrong on my side or with the server. Can't use other commputer to check it atm.

**Comment by StepKie** [comment]
Hi,

this is likely related to the fact that I changed my GitHub handle, and thus the associated generated github.io URLchanged as well.

https://stepkie.github.io/MtgCsvHelper/ should work.

I will update the README  to point to the URL asap.
